const express = require('express')
const todoroutes = require('./src/routes/todoRoutes')
const authRoutes=require('./src/routes/authroutes')
const fileRoutes=require('./src/routes/fileRotutes')
const {errorHandling}=require('./src/middleware/middleware')
require('dotenv').config()
const app = express()
app.use(express.json())
app.use('/todo', todoroutes)
app.use('/auth', authRoutes)
app.use('/file',fileRoutes)
app.use(errorHandling)
app.listen(process.env.PORT, () => { console.log(`server runnimg on port ${process.env.PORT}`) })